import type { Metadata } from "next";
import { Providers } from './providers';
import "./globals.css";

// Base HTML wrapper for non-locale routes (redirected by middleware)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
