import type { Metadata } from "next";
import { Providers } from './providers';
import { ThemeProvider } from './theme-provider';
import "./globals.css";

// Base HTML wrapper for non-locale routes (redirected by middleware)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof globalThis !== 'undefined') {
    const g = globalThis as any;
    if (!g.__deliveryCron) {
      g.__deliveryCron = setInterval(async () => {
        try {
          await fetch('http://localhost:3000/api/delivery/shipments/refresh', { method: 'POST' });
        } catch {}
      }, 60 * 1000 * 60 * 24);
    }
  }
  return (
    <html suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
