export type Role = 'owner'|'manager'|'cashier'|'staff'|'viewer';
export type Action =
  | 'POS.SALE' | 'POS.DISCOUNT_MANUAL' | 'POS.REFUND_CONFIRM' | 'POS.RETURN_EXCHANGE_FINALIZE'
  | 'POS.DRAWER_OPEN' | 'POS.END_SHIFT'
  | 'INVENTORY.ADJUST_POST' | 'INVENTORY.COUNT_POST'
  | 'PRODUCTS.CREATE' | 'PRODUCTS.UPDATE' | 'PRODUCTS.DELETE'
  | 'PROMOS.MANAGE' | 'TAX.MANAGE' | 'SETTINGS.MANAGE'
  | 'USERS.MANAGE' | 'AUDIT.VIEW';

export const ROLE_PERMS: Record<Role, Action[] | ['*']> = {
  owner: ['*'],
  manager: ['POS.SALE','POS.DISCOUNT_MANUAL','POS.REFUND_CONFIRM','POS.RETURN_EXCHANGE_FINALIZE','POS.DRAWER_OPEN','POS.END_SHIFT',
            'INVENTORY.ADJUST_POST','INVENTORY.COUNT_POST','PRODUCTS.CREATE','PRODUCTS.UPDATE','PRODUCTS.DELETE',
            'PROMOS.MANAGE','TAX.MANAGE','SETTINGS.MANAGE','USERS.MANAGE','AUDIT.VIEW'],
  cashier: ['POS.SALE','POS.DRAWER_OPEN','POS.END_SHIFT'],
  staff: ['INVENTORY.COUNT_POST','AUDIT.VIEW'],
  viewer: ['AUDIT.VIEW']
};

export const NEEDS_MANAGER: Action[] = [
  'POS.REFUND_CONFIRM','POS.RETURN_EXCHANGE_FINALIZE','INVENTORY.ADJUST_POST','PROMOS.MANAGE','TAX.MANAGE','PRODUCTS.DELETE'
];

export const MANUAL_DISCOUNT_LIMIT = 0.10; // 10%
