export type Role = 'owner'|'manager'|'cashier'|'staff'|'viewer';
export type Action =
  | 'POS.SALE' | 'POS.DISCOUNT_MANUAL' | 'POS.REFUND_CONFIRM' | 'POS.RETURN_EXCHANGE_FINALIZE'
  | 'POS.DRAWER_OPEN' | 'POS.END_SHIFT'
  | 'INVENTORY.ADJUST_POST' | 'INVENTORY.COUNT_POST'
  | 'INVENTORY.LOCATIONS_MANAGE' | 'INVENTORY.TRANSFER_CREATE' | 'INVENTORY.TRANSFER_APPROVE' | 'INVENTORY.TRANSFER_PICK' | 'INVENTORY.TRANSFER_DISPATCH' | 'INVENTORY.TRANSFER_RECEIVE' | 'INVENTORY.TRANSFER_CANCEL'
  | 'PRODUCTS.CREATE' | 'PRODUCTS.UPDATE' | 'PRODUCTS.DELETE'
  | 'CUSTOMERS.CREATE' | 'CUSTOMERS.UPDATE' | 'CUSTOMERS.DELETE' | 'CUSTOMERS.MERGE'
  | 'PROMOS.MANAGE' | 'TAX.MANAGE' | 'SETTINGS.MANAGE'
  | 'NOTIF.MANAGE' | 'NOTIF.SEND'
  | 'USERS.MANAGE' | 'AUDIT.VIEW';

export const ROLE_PERMS: Record<Role, Action[] | ['*']> = {
  owner: ['*'],
  manager: ['POS.SALE','POS.DISCOUNT_MANUAL','POS.REFUND_CONFIRM','POS.RETURN_EXCHANGE_FINALIZE','POS.DRAWER_OPEN','POS.END_SHIFT',
            'INVENTORY.ADJUST_POST','INVENTORY.COUNT_POST','INVENTORY.LOCATIONS_MANAGE','INVENTORY.TRANSFER_CREATE','INVENTORY.TRANSFER_APPROVE','INVENTORY.TRANSFER_PICK','INVENTORY.TRANSFER_DISPATCH','INVENTORY.TRANSFER_RECEIVE','INVENTORY.TRANSFER_CANCEL',
            'PRODUCTS.CREATE','PRODUCTS.UPDATE','PRODUCTS.DELETE',
            'CUSTOMERS.CREATE','CUSTOMERS.UPDATE','CUSTOMERS.DELETE','CUSTOMERS.MERGE',
            'PROMOS.MANAGE','TAX.MANAGE','SETTINGS.MANAGE','NOTIF.MANAGE','NOTIF.SEND','USERS.MANAGE','AUDIT.VIEW'],
  cashier: ['POS.SALE','POS.DRAWER_OPEN','POS.END_SHIFT','CUSTOMERS.CREATE','CUSTOMERS.UPDATE','NOTIF.SEND'],
  staff: ['INVENTORY.COUNT_POST','INVENTORY.TRANSFER_CREATE','INVENTORY.TRANSFER_PICK','INVENTORY.TRANSFER_RECEIVE','AUDIT.VIEW'],
  viewer: ['AUDIT.VIEW']
};

export const NEEDS_MANAGER: Action[] = [
  'POS.REFUND_CONFIRM','POS.RETURN_EXCHANGE_FINALIZE','INVENTORY.ADJUST_POST','INVENTORY.TRANSFER_APPROVE','INVENTORY.TRANSFER_DISPATCH','PROMOS.MANAGE','TAX.MANAGE','PRODUCTS.DELETE','CUSTOMERS.DELETE','CUSTOMERS.MERGE','NOTIF.MANAGE'
];

export const MANUAL_DISCOUNT_LIMIT = 0.10; // 10%
