name: Vercel Production

on:
  push:
    branches: [main, release/**]

permissions:
  contents: read

concurrency:
  group: vercel-prod-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Pull env
        working-directory: shop
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - name: Build
        working-directory: shop
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel build --prod --token=$VERCEL_TOKEN
      - name: Deploy
        working-directory: shop
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
